version: '3'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - rabbitmq
      - promtail
      - loki
      - grafana
    environment:
      RABBITMQ_BASE_URI: ${RABBITMQ_BASE_URI}
    ports:
      - 3000:3000
    volumes:
      - .:/app/rabbitmq-golang/
  rabbitmq:
    image: rabbitmq:3.11.2-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    ports:
      - 9080:9080
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./app.log:/app/log/*log
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yml:/etc/loki/local-config.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - promtail
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    user: "$UID:$GID"
    ports:
      - "3333:3000"
    volumes:
      # - ./data/grafana:/var/lib/grafana
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
